version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql2
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - samueldev_data:/var/lib/mysql

volumes:
  samueldev_data: